export const FETCH_IMAGES= "FETCH_IMAGES"
export const DELETE_IMAGE= "DELETE_IMAGE"
export const ERROR= "ERROR"
export const CLEAR_ERROR= "CLEAR_ERROR"
export const UPLOAD_IMAGE= "UPLOAD_IMAGE"
export const LOADING= "LOADING"
export const SAVING= "SAVING"
export const DELETION= "DELETION"